Feature/search result
WildCodeSchool/2022-03-JS-Reims-project-3-shop-around-me pull request #10
Opened 2022-06-02 15:03 UTC by Simon-Duc

2022-06-02 15:15 UTC, nibor51 requested changes

2022-06-02 15:15 UTC, nibor51 commented on frontend/src/pages/Home.jsx
> +    console.warn(searchValue.current.value);
delete or comment to justify

2022-06-03 08:31 UTC, rocambille requested changes

2022-06-03 08:31 UTC, rocambille commented on frontend/src/components/SearchBar.jsx
> +          .filter((result) => result.name.includes(searchValue.current.value))
the filter should be done on server side

2022-06-14 08:32 UTC, rocambille requested changes

2022-06-14 08:32 UTC, rocambille commented on backend/src/models/AbstractManager.js
> +      `select * from  ${this.table} WHERE name LIKE '%${research}%' OR brand LIKE '%${research}%'`
congratulations, you just allowed SQL injections :p

https://www.w3schools.com/sql/sql_injection.asp

use markers `?` to inject values in SQL in a secure way

2022-06-14 08:32 UTC, rocambille commented on backend/src/controllers/ProductController.js
> +      .findSearch(req.query.search)
`search` instead of `findSearch` would be a better name, or `findByQuery`

2022-06-14 10:25 UTC, nibor51 commented
conflic to resolve

2022-06-14 15:17 UTC, rocambille requested changes

2022-06-14 15:17 UTC, rocambille commented on frontend/src/components/SearchBar.jsx
> +        `http://localhost:5001/products/?search=${searchValue.current.value}`
use env variables instead of magic values ;)

2022-06-15 09:08 UTC, merged