Feature/inscription form
WildCodeSchool/2022-03-JS-Reims-project-3-shop-around-me pull request #27
Opened 2022-06-16 15:34 UTC by Alexandra-Rdrgs

Formulaire d'inscription sans connexion au back.

2022-06-17 07:52 UTC, nibor51 requested changes
Tty to use a variable for repeating classNames ["text-red-600 normal-case text-xs font-normal italic"]
it will be easier to maintain

2022-06-22 08:29 UTC, rocambille requested changes

2022-06-22 08:29 UTC, rocambille commented on frontend/src/components/InscriptionForm.jsx
> +            <label className="form-label" htmlFor="grid-firstname">
try to merge the div and the label

2022-06-22 09:43 UTC, Alexandra-Rdrgs commented
The changes requested have been made

2022-06-22 09:53 UTC, rocambille commented on frontend/src/components/InscriptionForm.jsx
> +        </div>
another p to replace div+span ?

2022-06-22 09:55 UTC, rocambille commented on frontend/src/components/InscriptionForm.jsx
> +          )}
p are not allowed in labels : put them outside

2022-06-22 13:27 UTC, merged